In [2]:
import torch
print(torch.__version__)


2.11.0+cpu


In [3]:
if torch.cude.is_avaible():
  print("GPu is available")
else:
  print("Gpu is not avaible")

AttributeError: module 'torch' has no attribute 'cude'

In [4]:
import torch

if torch.cuda.is_available():
    print("GPU is available")
else:
    print("GPU is not available")

GPU is not available


In [2]:
torch.empty(2,33)

NameError: name 'torch' is not defined

In [1]:
import torch

if torch.cuda.is_available():
  print("GPU is availble")


else:
  print("GPU is not available")


GPU is availble


In [2]:
import torch
if torch.cuda.is_available():
  print("GPU is available")

else:
  print("GPU is not available")

GPU is available


In [5]:
# Creating a tensor

#creating a tensor


In [6]:
torch.empty(2,3)

tensor([[-7.8635e+07,  4.3436e-41,  9.9705e-33],
        [ 4.3439e-41,  1.6339e-38,  0.0000e+00]])

In [2]:
import torch
a = torch.empty(22,33)

In [3]:
type(a)

torch.Tensor

In [4]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [5]:
torch.zeros(2,3)


tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
a = torch.rand(2,4)

In [13]:
type(a)

torch.Tensor

In [16]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])